### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by putsy-caballero** [mdsteele/syzygy#2]
https://github.com/mdsteele/syzygy/blob/1e06063f548f026e4e3a5c9309a3af8bf2e4f8a9/src/modes/prolog/scenes.rs#L105

should be "Urgent"

**Comment by putsy-caballero** [comment]
actually I can't tell. maybe I'm not far enough in the story, someone else just called him Ugrent, but he introduced himself as Urgent I think?

**Comment by mdsteele** [comment]
"Ugrent" is the correct spelling of his name.  (Yes, it's a weird name.)

I just double-checked, and the string "Urgent" doesn't appear anywhere in the code (even ignoring case).
