### ISSUE TITLE
Immediate panic when compiled with Rust 1.48

### ISSUE THREAD

**Issue by michaelcmartin** [mdsteele/syzygy#9]
If you build and run with the latest version of Rust, the main thread panics immediately after the window is created.

This appears to be due to a change in how uninitialized memory is handled in `unsafe` code:

[`mem::uninitialized` will now panic if any inner types inside a struct or enum disallow zero-initialization.](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#compatibility-notes)

This seems to be an issue with your fork of Rust-SDL2: [upstream patched it as part of version 0.33](https://github.com/Rust-SDL2/rust-sdl2/commit/3c5fcdc05efb3b1d220a7c6bb86276281a0c8811).

The simplest workaround would simply be to note in the README that one should stick to rustc 1.47; a more aggressive fix would be to update your SDL2 fork to patch on top of the latest 0.34.2,

**Comment by mdsteele** [comment]
Thanks very much for tracking this down.  I believe that the Rust-SDL2 fork is there because at the time I needed a fix that hadn't yet been merged in, but the need for that fork has long since passed.  I'll try updating the sdl2 crate dependency to v0.34.
